export interface StatePropertyTax {
    state: string;
    abbreviation: string;
    rate: number; // Effective property tax rate as a decimal
}

export const propertyTaxRates: StatePropertyTax[] = [
    { state: "Alabama", abbreviation: "AL", rate: 0.0040 },
    { state: "Alaska", abbreviation: "AK", rate: 0.0104 },
    { state: "Arizona", abbreviation: "AZ", rate: 0.0063 },
    { state: "Arkansas", abbreviation: "AR", rate: 0.0064 },
    { state: "California", abbreviation: "CA", rate: 0.0075 },
    { state: "Colorado", abbreviation: "CO", rate: 0.0055 },
    { state: "Connecticut", abbreviation: "CT", rate: 0.0179 },
    { state: "Delaware", abbreviation: "DE", rate: 0.0061 },
    { state: "Florida", abbreviation: "FL", rate: 0.0091 },
    { state: "Georgia", abbreviation: "GA", rate: 0.0092 },
    { state: "Hawaii", abbreviation: "HI", rate: 0.0032 },
    { state: "Idaho", abbreviation: "ID", rate: 0.0067 },
    { state: "Illinois", abbreviation: "IL", rate: 0.0208 },
    { state: "Indiana", abbreviation: "IN", rate: 0.0084 },
    { state: "Iowa", abbreviation: "IA", rate: 0.0152 },
    { state: "Kansas", abbreviation: "KS", rate: 0.0134 },
    { state: "Kentucky", abbreviation: "KY", rate: 0.0083 },
    { state: "Louisiana", abbreviation: "LA", rate: 0.0056 },
    { state: "Maine", abbreviation: "ME", rate: 0.0124 },
    { state: "Maryland", abbreviation: "MD", rate: 0.0105 },
    { state: "Massachusetts", abbreviation: "MA", rate: 0.0114 },
    { state: "Michigan", abbreviation: "MI", rate: 0.0138 },
    { state: "Minnesota", abbreviation: "MN", rate: 0.0111 },
    { state: "Mississippi", abbreviation: "MS", rate: 0.0067 },
    { state: "Missouri", abbreviation: "MO", rate: 0.0101 },
    { state: "Montana", abbreviation: "MT", rate: 0.0074 },
    { state: "Nebraska", abbreviation: "NE", rate: 0.0163 },
    { state: "Nevada", abbreviation: "NV", rate: 0.0059 },
    { state: "New Hampshire", abbreviation: "NH", rate: 0.0193 },
    { state: "New Jersey", abbreviation: "NJ", rate: 0.0223 },
    { state: "New Mexico", abbreviation: "NM", rate: 0.0067 },
    { state: "New York", abbreviation: "NY", rate: 0.0140 },
    { state: "North Carolina", abbreviation: "NC", rate: 0.0082 },
    { state: "North Dakota", abbreviation: "ND", rate: 0.0098 },
    { state: "Ohio", abbreviation: "OH", rate: 0.0159 },
    { state: "Oklahoma", abbreviation: "OK", rate: 0.0089 },
    { state: "Oregon", abbreviation: "OR", rate: 0.0093 },
    { state: "Pennsylvania", abbreviation: "PA", rate: 0.0149 },
    { state: "Rhode Island", abbreviation: "RI", rate: 0.0140 },
    { state: "South Carolina", abbreviation: "SC", rate: 0.0057 },
    { state: "South Dakota", abbreviation: "SD", rate: 0.0117 },
    { state: "Tennessee", abbreviation: "TN", rate: 0.0067 },
    { state: "Texas", abbreviation: "TX", rate: 0.0168 },
    { state: "Utah", abbreviation: "UT", rate: 0.0057 },
    { state: "Vermont", abbreviation: "VT", rate: 0.0183 },
    { state: "Virginia", abbreviation: "VA", rate: 0.0087 },
    { state: "Washington", abbreviation: "WA", rate: 0.0087 },
    { state: "West Virginia", abbreviation: "WV", rate: 0.0057 },
    { state: "Wisconsin", abbreviation: "WI", rate: 0.0161 },
    { state: "Wyoming", abbreviation: "WY", rate: 0.0056 },
    { state: "District of Columbia", abbreviation: "DC", rate: 0.0058 },
];
